### ISSUE TITLE
Some odd unicode glyphs are mangled

### ISSUE THREAD

**Issue by kadoban** [kgsHtml/kgs-html-issues#6] opened 2015-01-02 08:06 UTC
At least some glyphs aren't coming through to the HTML client. Most seem to work fine (At least the room names for the Japanese, Chinese, Israeli and Korean rooms), but for example the go stones in the Empty Sky room description render as "?" instead.

It's not a font issue, or at least it's not a browser font issue, the actual text is replaced with hard "?"s when you view the source of the website.

We should investigate why that's happening, if for no other reason than to figure out if it will affect anything important.

**Comment by wshubert** [comment] 2015-01-03 06:01
I checked, when sending text I filter all <, &, etc. characters to be the appropriate substitutions. All other characters are passed through unchanged.

I wonder, is this a problem caused by java's 16 bit unicode representations? Does java use the surrogate system for them? Maybe when I go through these one character at a time, they get mangled. Not sure how I would fix that.

**Comment by wshubert** [comment] 2017-03-22 00:47
No more dojoclient! Closing out.

**Closed as completed by wshubert** 2017-03-22 00:47 UTC
